### PR TITLE
fix(1173): Record wait time for all reducers

### LINKED ISSUE #1173: Fix reducer wait time metric
At the moment we're only recording this metric for scheduled reducers. We should be recording it for all reducers. We're also recording it before we acquire the module instance semaphore.

### PR DESCRIPTION
**Pull request by joshua-spacetime**
Fixes #1173.

Previously we were only recording this metric for scheduled reducers. We were also recording it before we acquired access to the module instance. Now we record it for all reducers after we acquire access to the module instance.

This patch also removes max wait time since the histogram should suffice.

# Description of Changes

Please describe your change, mention any related tickets, and so on here.

# API and ABI breaking changes

If this is an API or ABI breaking change, please apply the
corresponding GitHub label.

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

# Testing

*Describe any testing you've done, and any testing you'd like your reviewers to do,
so that you're confident that all the changes work as expected!*

- [x] *Write a test you've completed here.*
- [ ] *Write a test you want a reviewer to do here, so they can check it off when they're satisfied.*

### CODE REVIEW

File: crates/core/src/host/module_host.rs [hunk 1]
```diff
@@ -636,12 +637,19 @@ impl ModuleHost {
...
         R: Send + 'static,
     {
-        let mut inst = self.inner.get_instance(self.info.address).await?;
+        let mut inst = {
+            // Record the time spent waiting in the queue
+            let _guard = WORKER_METRICS
+                .reducer_wait_time
+                .with_label_values(&self.info.address, reducer)
+                .start_timer();
+            self.inner.get_instance(self.info.address).await?
```
Comment (joshua-spacetime) [inline crates/core/src/host/module_host.rs:651]: @coolreader18 do you agree that this is the correct place to be recording this metric? And that this works for all reducers?

Comment (coolreader18) [reply crates/core/src/host/module_host.rs:651]: for all reducers and for other such calls. but yeah, this seems right.

**Review by coolreader18 — APPROVED** [review]
