### PR TITLE
fix(1170): Use scope guard to decrement reducer queue length

### LINKED ISSUE #1170: Fix reducer queue length metric
It's still not correct

### PR DESCRIPTION
**Pull request by joshua-spacetime**
Fixes #1170.

Also updates the bucket values for the queue length histogram. Also removes the max queue length metric, since the histogram should suffice.

# Description of Changes

Please describe your change, mention any related tickets, and so on here.

# API and ABI breaking changes

If this is an API or ABI breaking change, please apply the
corresponding GitHub label.

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

# Testing

*Describe any testing you've done, and any testing you'd like your reviewers to do,
so that you're confident that all the changes work as expected!*

- [x] *Write a test you've completed here.*
- [ ] *Write a test you want a reviewer to do here, so they can check it off when they're satisfied.*

### CODE REVIEW

File: crates/core/src/util/lending_pool.rs [hunk 1]
```diff
@@ -58,31 +87,9 @@ impl<T> LendingPool<T> {
...
-                }
-            })
-            .or_insert_with(|| new_queue_len);
-
-        drop(guard);
-        queue_len_max.set(max_queue_len);
-
         async move {
+            let _guard = QueueMetric::inc(db);
             let permit = acq.await.map_err(|_| PoolClosed)?;
```
Comment (joshua-spacetime) [inline crates/core/src/util/lending_pool.rs:92]: I'm fairly confident we should not have any more issues with this metric not resetting, or this metric going negative, with this scope guard in place.

File: crates/core/src/util/lending_pool.rs [hunk 2]
```diff
@@ -49,6 +49,35 @@ struct PoolVec<T> {
...
+}
+
+impl Drop for QueueMetric {
+    fn drop(&mut self) {
+        WORKER_METRICS.instance_queue_length.with_label_values(&self.db).dec();
+        let queue_length = WORKER_METRICS.instance_queue_length.with_label_values(&self.db).get();
+        WORKER_METRICS
+            .instance_queue_length_histogram
+            .with_label_values(&self.db)
+            .observe(queue_length as f64);
```
Comment (coolreader18) [inline crates/core/src/util/lending_pool.rs:65]: why do we need a separate histogram? shouldn't grafana accumulate the data for us over time anyway?

**Review by coolreader18 — APPROVED** [review]
LGTM!

File: crates/core/src/util/lending_pool.rs (hunk 2 above)
Comment (coolreader18) [reply crates/core/src/util/lending_pool.rs:65]: if you didn't need to se the histogram you could just use the `inc_scope` utility function I made a while ago, which does this same sorta thing.

Comment (joshua-spacetime) [reply crates/core/src/util/lending_pool.rs:65]: > why do we need a separate histogram? shouldn't grafana accumulate the data for us over time anyway?

The `instance_queue_length` metric is a gauge which is only sampled once per sampling interval. So all it gives us is the queue length at the end of the sampling interval over time. But it doesn't tell us anything about the queue length at the beginning or middle of the sampling interval.

`instance_queue_length_histogram` on the other hand will build a histogram of all the different values the queue length takes throughout the sampling interval, and this will give us percentiles.

It is true that `instance_queue_length` really doesn't give us any new information over the histogram. We just need some variable to track the current length of the queue. I just chose a prometheus metric for that purpose mainly for ease of use.

Comment (joshua-spacetime) [reply crates/core/src/util/lending_pool.rs:65]: > you could just use the inc_scope utility function I made a while ago

I would have done that if it weren't for the `get`
