### PR TITLE
fix(684): Reset max value metrics

### LINKED ISSUE #684: Max cpu time is not resetting
Image

The maximum transaction cpu time is not resetting. Note that the maximum queue length is resetting which is the correct behavior.

Image

### PR DESCRIPTION
**Pull request by joshua-spacetime**
Fixes #684.

Prometheus does not reset metrics.
It only updates them with new values that it collects. If it does not receive a new value for a metric, it will keep the old value.

Therefore it is important to periodically reset certain metrics. Namely gauge metrics that only receive updates occasionally.

Maximum reducer duration is one such example,
since some reducers run much more infrequently than others.

# Description of Changes

Please describe your change, mention any related tickets, and so on here.

# API and ABI breaking changes

If this is an API or ABI breaking change, please apply the
corresponding GitHub label.

# Expected complexity level and risk

*How complicated do you think these changes are? Grade on a scale from 1 to 5,
where 1 is a trivial change, and 5 is a deep-reaching and complex change.*

*This complexity rating applies not only to the complexity apparent in the diff,
but also to its interactions with existing and future code.*

*If you answered more than a 2, explain what is complex about the PR,
and what other components it interacts with in potentially concerning ways.*

### CODE REVIEW

File: crates/core/src/db/datastore/locking_tx_datastore/mod.rs [hunk 1]
```diff
@@ -2399,18 +2397,9 @@ impl traits::MutTx for Locking {
...
-            a.hash(&mut hasher);
-            b.hash(&mut hasher);
-            c.hash(&mut hasher);
-            hasher.finish()
-        }
-
         let mut guard = MAX_TX_CPU_TIME.lock().unwrap();
         let max_cpu_time = *guard
-            .entry(hash(workload, db, reducer))
+            .entry((*db, *workload, reducer.to_owned()))
```
Comment (joshua-spacetime) [inline crates/core/src/db/datastore/locking_tx_datastore/mod.rs:2402]: This was an optimization to avoid extra allocations when recording metrics. But I'd rather take the allocations than deal with a potential hash collision when debugging a performance issue.

**Review by cloutiertyler — APPROVED** [review]
LGTM
