### PR TITLE
fix automigration bug with `auto_inc`

### LINKED ISSUE #3861: automigration: Server panics when if `primary_key` column is annotated with `auto_inc` as well.
reported: https://discord.com/channels/1037340874172014652/1138987509834059867/1448097717111885915.

Repro:

1. publish this module:
```rust
#[spacetimedb::table(name = user, public)]
pub struct User {
    #[primary_key]
    id: u32,
}
```

2. Now add `[auto_inc]` and publish again
```rust
#[spacetimedb::table(name = user, public)]
pub struct User {
    #[primary_key]
    #[auto_inc]
    id: u32,
}
```

3. It hits the `expect` here - https://github.com/clockworklabs/SpacetimeDB/blob/master/crates/table/src/table_index/mod.rs#L845
in `um_iter_at_type`

Server log with Backtrace:
```
2025-12-10T08:18:01.308019Z  INFO crates/core/src/db/update.rs:97: Running database update prechecks: c200d799f3189ffdc9e9705b6c104286241c5e9bfb2fef8cdabebe6d01c175b8

thread 'tokio-runtime-worker' panicked at /home/shub/me/clock/SpacetimeDBPrivate/public/crates/table/src/table_index/mod.rs:845:42:
bound does not conform to key type of index
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/panicking.rs:268:5
   3: core::option::expect_failed
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/option.rs:2139:5
   4: core::option::Option<T>::expect
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:964:21
   5: spacetimedb_table::table_index::TypedIndex::seek_range::um_iter_at_type::{{closure}}
             at ./crates/table/src/table_index/mod.rs:845:42
   6: core::ops::function::FnOnce::call_once
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:253:5
   7: core::ops::range::Bound<T>::map
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/range.rs:733:37
   8: spacetimedb_table::table_index::TypedIndex::seek_range::um_iter_at_type
             at ./crates/table/src/table_index/mod.rs:846:45
   9: spacetimedb_table::table_index::TypedIndex::seek_range
             at ./crates/table/src/table_index/mod.rs:889:58
  10: spacetimedb_table::table_index::TableIndex::seek_range
             at ./crates/table/src/table_index/mod.rs:1235:28
  11: spacetimedb_table::table::TableAndIndex::seek_range
             at ./crates/table/src/table.rs:2086:42
  12: spacetimedb_datastore::locking_tx_datastore::committed_state::CommittedState::index_seek::{{closure}}
             at ./crates/datastore/src/locking_tx_datastore/committed_state.rs:619:24
  13: core::option::Option<T>::map
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1158:29
  14: spacetimedb_datastore::locking_tx_datastore::committed_state::CommittedState::index_seek
             at ./crates/datastore/src/locking_tx_datastore/committed_state.rs:619:14
  15: spacetimedb_datastore::locking_tx_datastore::mut_tx::iter_by_col_range
             at ./crates/datastore/src/locking_tx_datastore/mut_tx.rs:3016:48
  16: <spacetimedb_datastore::locking_tx_datastore::mut_tx::MutTxId as spacetimedb_datastore::locking_tx_datastore::state_view::StateView>::iter_by_col_range
             at ./crates/datastore/src/locking_tx_datastore/mut_tx.rs:2977:9
  17: <spacetimedb_datastore::locking_tx_datastore::datastore::Locking as spacetimedb_datastore::traits::MutTxDatastore>::iter_by_col_range_mut_tx
             at ./crates/datastore/src/locking_tx_datastore/datastore.rs:577:12
  18: spacetimedb::db::relational_db::RelationalDB::iter_by_col_range_mut
             at ./crates/core/src/db/relational_db.rs:1407:23
  19: spacetimedb::db::update::auto_migrate_database
             at ./crates/core/src/db/update.rs:115:22
  20: spacetimedb::db::update::update_database
             at ./crates/core/src/db/update.rs:67:36
  21: spacetimedb::host::wasm_common::module_host_actor::InstanceCommon::update_database
             at ./crates/core/src/host/wasm_common/module_host_actor.rs:543:19
  22: spacetimedb::host::wasm_common::module_host_actor::WasmModuleInstance<T>::update_database
             at ./crates/core/src/host/wasm_common/module_host_actor.rs:393:14
  23: spacetimedb::host::module_host::ModuleHost::update_database::{{closure}}::{{closure}}
             at ./crates/core/src/host/module_host.rs:1819:36
  24: spacetimedb::host::module_host::ModuleHost::call::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/core/src/host/module_host.rs:1155:34
  25: spacetimedb::util::jobs::SingleCoreExecutor::run_sync_job::{{closure}}::{{closure}}
             at ./crates/core/src/util/jobs.rs:334:30
  26: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/core.rs:365:24
  27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/loom/std/unsafe_cell.rs:16:9
  28: tokio::runtime::task::core::Core<T,S>::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/core.rs:354:30
  29: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:535:30
  30: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  31: std::panicking::catch_unwind::do_call
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  32: __rust_try
  33: std::panicking::catch_unwind
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
  34: std::panic::catch_unwind
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  35: tokio::runtime::task::harness::poll_future
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:523:18
  36: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:210:27
  37: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:155:20
  38: tokio::runtime::task::raw::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/raw.rs:325:13
  39: tokio::runtime::task::raw::RawTask::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/raw.rs:255:18
  40: tokio::runtime::task::LocalNotified<S>::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/mod.rs:509:13
  41: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:600:18
  42: tokio::task::coop::with_budget
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/task/coop/mod.rs:167:5
  43: tokio::task::coop::budget
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/task/coop/mod.rs:133:5
  44: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:591:9
  45: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:539:29
  46: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:504:24
  47: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/context/scoped.rs:40:9
  48: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/context.rs:176:38
  49: std::thread::local::LocalKey<T>::try_with
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:315:12
  50: std::thread::local::LocalKey<T>::with
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:279:20
  51: tokio::runtime::context::set_scheduler
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/context.rs:176:17
  52: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:499:9
  53: tokio::runtime::context::runtime::enter_runtime
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/context/runtime.rs:65:16
  54: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:491:5
  55: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/scheduler/multi_thread/worker.rs:457:45
  56: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/blocking/task.rs:42:21
  57: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/core.rs:365:24
  58: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/loom/std/unsafe_cell.rs:16:9
  59: tokio::runtime::task::core::Core<T,S>::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/core.rs:354:30
  60: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:535:30
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  62: std::panicking::catch_unwind::do_call
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  63: __rust_try
  64: std::panicking::catch_unwind
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
  65: std::panic::catch_unwind
             at /home/shub/.rustup/toolchains/1.90.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  66: tokio::runtime::task::harness::poll_future
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:523:18
  67: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:210:27
  68: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/harness.rs:155:20
  69: tokio::runtime::task::raw::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/raw.rs:325:13
  70: tokio::runtime::task::raw::RawTask::poll
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/raw.rs:255:18
  71: tokio::runtime::task::UnownedTask<S>::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/task/mod.rs:546:13
  72: tokio::runtime::blocking::pool::Task::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/blocking/pool.rs:161:19
  73: tokio::runtime::blocking::pool::Inner::run
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/blocking/pool.rs:516:22
  74: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/shub/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.48.0/src/runtime/blocking/pool.rs:474:47
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by Shubham8287**
# Description of Changes
fixes #3861.

While running prechecks for automigration, the `range` passed to `iter_by_col_range_mut` was of type `AlgebraicValue::I128`, even though it should have matched the column’s type.

Fix is straightforward by introducing `AlgebraicValue::from_i128` helper.

# API and ABI breaking changes
NA

# Expected complexity level and risk
1

# Testing

- Modified smoketest to repro reported bug.

### CODE REVIEW

File: crates/sats/src/algebraic_value.rs [hunk 1]
```diff
@@ -276,6 +276,30 @@ impl AlgebraicValue {
...
+    ///
+    /// Returns `None` if the type is not a supported integer type.
+    pub fn from_i128(ty: &AlgebraicType, value: i128) -> Option<Self> {
+        let val = match ty {
+            AlgebraicType::I8 => Self::I8(value as i8),
+            AlgebraicType::I16 => Self::I16(value as i16),
+            AlgebraicType::I32 => Self::I32(value as i32),
+            AlgebraicType::I64 => Self::I64(value as i64),
+            AlgebraicType::I128 => Self::I128(Packed(value)),
+            AlgebraicType::I256 => Self::I256(Box::new(i256::from(value))),
```
Comment (Centril) [inline crates/sats/src/algebraic_value.rs]:
```suggestion
            AlgebraicType::I8 => (value as i8).into(),
            AlgebraicType::I16 => (value as i16).into(),
            AlgebraicType::I32 => (value as i32).into(),
            AlgebraicType::I64 => (value as i64).into(),
            AlgebraicType::I128 => value.into(),
            AlgebraicType::I256 => i256::from(value).into(),
```

File: crates/sats/src/algebraic_value.rs [hunk 2]
```diff
@@ -276,6 +276,30 @@ impl AlgebraicValue {
...
+
+            AlgebraicType::U8 => Self::U8(value as u8),
+            AlgebraicType::U16 => Self::U16(value as u16),
+            AlgebraicType::U32 => Self::U32(value as u32),
+            AlgebraicType::U64 => Self::U64(value as u64),
+            AlgebraicType::U128 => Self::U128(Packed(value as u128)),
+            AlgebraicType::U256 => Self::U256(Box::new(u256::from(value as u128))),
```
Comment (Centril) [inline crates/sats/src/algebraic_value.rs]:
```suggestion
            AlgebraicType::U8 => (value as u8).into(),
            AlgebraicType::U16 => (value as u16).into(),
            AlgebraicType::U32 => (value as u32).into(),
            AlgebraicType::U64 => (value as u64).into(),
            AlgebraicType::U128 => (value as u128).into(),
            AlgebraicType::U256 => (u256::from(value as u128)).into(),
```
