### PR TITLE
Fix bench for location, restore single-column indexes

### LINKED ISSUE #965: Fix subscription benchmarks
The `full-join` and `incr-join` benchmarks regressed when multi-column index support was added as the single column index on the `chunk_index` column was removed.

### PR DESCRIPTION
**Pull request by mamcx**
# Description of Changes

Revert regression on `bench` for location, restoring the creation of single-column indexes.

Closes [965](https://github.com/clockworklabs/SpacetimeDB/issues/965)

# Expected complexity level and risk

1

### CODE REVIEW

File: crates/bench/benches/subscription.rs [hunk 1]
```diff
@@ -18,7 +18,10 @@ fn create_table_location(db: &RelationalDB) -> Result<TableId, DBError> {
         ("z", AlgebraicType::I32),
         ("dimension", AlgebraicType::U32),
     ];
-    db.create_table_for_test_multi_column("location", schema, col_list![2, 3, 4])
+    let indexes = &[(0.into(), "entity_id"), (2.into(), "owner_entity_id")];
```
Comment (joshua-spacetime) [inline crates/bench/benches/subscription.rs:21]: I think you meant 0 and 1 for entity_id and chunk_index.

Comment (mamcx) [reply crates/bench/benches/subscription.rs:21]: Correct

**Review by joshua-spacetime — APPROVED** [review]

**Review by kazimuth — COMMENTED** [review]
👍
